# Auto-generated by ESBMC (example output)
# Original file: example.py

from example import *
import pytest

@pytest.mark.parametrize("x,y", [
    (5, 3),    # Test case 1
])
def test_add_positive(x, y):
    """Auto-generated test cases for add_positive()"""
    add_positive(x, y)
