# Auto-generated by ESBMC (example output)
# Original file: example.py

from example import *
import pytest

@pytest.mark.parametrize("a", [
    (5),    # Test case 1
])
def test_check_positive(a):
    """Auto-generated test cases for check_positive()"""
    check_positive(a)
